### ISSUE TITLE
有遇到期望轨迹穿过地形的问题吗

### ISSUE THREAD

**Issue by JACKLiuDay** [NaCl-1374/perceptive_legged_control#1]
作者你好，感谢分享这么棒的开源工作。我在部署廖的那套 legged_perceptive 代码时，仿真里运行还挺正常的。在实体狗上部署的时候，发现期望的轨迹有时候会出现穿越地形的情况，导致实物部署的时候腿有时候会穿过楼梯，实验时候的表现为，狗腿直接踢到楼梯上，但这种情况是偶尔出现的。我在ETH论文里看到他们也提到了这个现象，你有什么好的思路和建议吗
![d5360e1f76c25027baca3c26eee4df7](https://github.com/user-attachments/assets/b3b93f70-a421-4bcf-8875-4233d3008092)
![5b826174a1512b85a155ac26dff258f](https://github.com/user-attachments/assets/e02ae4ec-579a-4e46-993f-5f260f10fbcc)
![af9a329dfd532ed2029c84d33a686c8](https://github.com/user-attachments/assets/cc9f385c-a4f6-4007-96fc-e530210e9e04)
![image](https://github.com/user-attachments/assets/1d42797c-a3aa-4bc3-b5cc-acfe11ee8e9a)

**Comment by NaCl-1374** [comment]
mcp计算出的轨迹干涉，看你这个轨迹扭曲的程度，像是求解时间不够的样子

**Comment by JACKLiuDay** [comment]
> mcp计算出的轨迹干涉，看你这个轨迹扭曲的程度，像是求解时间不够的样子

求解时间不够是什么原因啊，和控制器的算力有关系吗

**Comment by NaCl-1374** [comment]
> > mcp计算出的轨迹干涉，看你这个轨迹扭曲的程度，像是求解时间不够的样子
> 
> 求解时间不够是什么原因啊，和控制器的算力有关系吗

控制器算力越高越好，高程图推荐用另外的计算机跑gpu版的。

**Comment by JACKLiuDay** [comment]
> > > mcp计算出的轨迹干涉，看你这个轨迹扭曲的程度，像是求解时间不够的样子
> > 
> > 
> > 求解时间不够是什么原因啊，和控制器的算力有关系吗
> 
> 控制器算力越高越好，高程图推荐用另外的计算机跑gpu版的。

我用一个NUC(1260P，12代的处理器)，同时跑的定位算法(SLAM提供的估计，FASTLIO)，高程图(CPU版本的，高程图测试的时候能在10hz左右刷新)，还有perceptive这套算法，是不是有点超算力了。你有尝试过在实物部署吗

**Comment by NaCl-1374** [comment]
> > > > mcp计算出的轨迹干涉，看你这个轨迹扭曲的程度，像是求解时间不够的样子
> > > 
> > > 
> > > 求解时间不够是什么原因啊，和控制器的算力有关系吗
> > 
> > 
> > 控制器算力越高越好，高程图推荐用另外的计算机跑gpu版的。
> 
> 我用一个NUC(1260P，12代的处理器)，同时跑的定位算法(SLAM提供的估计，FASTLIO)，高程图(CPU版本的，高程图测试的时候能在10hz左右刷新)，还有perceptive这套算法，是不是有点超算力了。你有尝试过在实物部署吗

是的，你跑这么多东西，不超时才怪了😂。cpu跑满，控制器实时性根本不能保证。还有就是部署效果不太好。很吃定位。

**Comment by JACKLiuDay** [comment]
> > > > > mcp计算出的轨迹干涉，看你这个轨迹扭曲的程度，像是求解时间不够的样子
> > > > 
> > > > 
> > > > 求解时间不够是什么原因啊，和控制器的算力有关系吗
> > > 
> > > 
> > > 控制器算力越高越好，高程图推荐用另外的计算机跑gpu版的。
> > 
> > 
> > 我用一个NUC(1260P，12代的处理器)，同时跑的定位算法(SLAM提供的估计，FASTLIO)，高程图(CPU版本的，高程图测试的时候能在10hz左右刷新)，还有perceptive这套算法，是不是有点超算力了。你有尝试过在实物部署吗
> 
> 是的，你跑这么多东西，不超时才怪了😂。cpu跑满，控制器实时性根本不能保证。还有就是部署效果不太好。很吃定位。

一会我上实物在NUC看下htop，CPU占用啥情况，哈哈。我的部署效果也不好，刚开始也是怀疑定位有问题，用FASTLIO提供估计，但是和狗的估计融合总是有误差存在，处理成一样的以后，结果足端规划的期望轨迹又像图里这样。我现在只要期望轨迹乱就上不去台阶，期望轨迹不乱的话倒还好。

**Comment by JACKLiuDay** [comment]
我试了下，期望轨迹错乱和NUC算力没太大关系，算力是足够的，这些算法都跑起来，CPU还有余量。倒是出现个很奇怪的现象，实物实验的时候，狗腿偶尔会跟不上摆动腿规划的期望轨迹，导致提前触地，提前触地就摔楼梯上了。

<img width="400" alt="1732259751917" src="https://github.com/user-attachments/assets/2058460c-db0b-44ed-a6ad-548cfe9569ad">
橘黄色轨迹最后一下没跟上

**Comment by Timelees** [comment]
> 我试了下，期望轨迹错乱和NUC算力没太大关系，算力是足够的，这些算法都跑起来，CPU还有余量。倒是出现个很奇怪的现象，实物实验的时候，狗腿偶尔会跟不上摆动腿规划的期望轨迹，导致提前触地，提前触地就摔楼梯上了。
> <img alt="1732259751917" width="400" src="https://private-user-images.githubusercontent.com/30967867/388839626-2058460c-db0b-44ed-a6ad-548cfe9569ad.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTcyOTYxNTksIm5iZiI6MTc1NzI5NTg1OSwicGF0aCI6Ii8zMDk2Nzg2Ny8zODg4Mzk2MjYtMjA1ODQ2MGMtZGIwYi00NGVkLWE2YWQtNTQ4Y2ZlOTU2OWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTA4VDAxNDQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NWRjNmRkZTU0NzU3M2E0NDU1ZWRjNmY5N2YyN2YwNjU4ZTllN2EwNTk0YjcxMTc4ZjcxYzc3NTJkZTk2ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.C8iDWqUw0Bf6CzZeEeYL3s59KlvNWT1iUFCUAR_O4BA"> 橘黄色轨迹最后一下没跟上

腿无法跟上规划的期望轨迹是什么原因导致的呢？可以如何解决
